In [13]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

df = pd.read_csv("Bangladesh_database_Final_Merged_30features.csv")

df.head()

,FPAR,Avg_Salinity_Index,EVI,Rain_Temp_Ratio,Rainfall,Wind_Mean,Temp_Min,Wind_Max,Temp_Max,District,Clay,LAI,Nitrogen,Soil_Moisture_mm,pH,LST_Kelvin,Dominant_Soil_Texture,AP Ratio,Temp_Mean,Avg Humidity,Heat_Stress_Days,Silt,Growth,CN_Ratio,Crop Name,Organic_Carbon,Transplant,Season,NDVI_Season_Mean
0,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,28.25,2.968781,3.89,12.078043,5.73,297.294525,Loamy (Thịt/Phù sa),0.7722007722,19.631500,55.0,0,49.52,Jan to March,8.73,Wheat,33.97,Dec,Rabi,0.511809
1,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,28.25,2.968781,3.89,12.078043,5.73,297.294525,Loamy (Thịt/Phù sa),2.247030879,19.631500,60.0,0,49.52,Jan to March,8.73,Maize 2,33.97,Dec,Rabi,0.511809
2,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,28.25,2.968781,3.89,12.078043,5.73,297.294525,Loamy (Thịt/Phù sa),1.847881242,19.631500,72.5,0,49.52,Dec to March,8.73,Boro,33.97,Nov,Rabi,0.511809
3,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,28.25,2.968781,3.89,12.078043,5.73,297.294525,Loamy (Thịt/Phù sa),3.50877193,19.631500,80.0,0,49.52,Dec to March,8.73,Sweet Potato,33.97,Nov,Rabi,0.511809
4,4.169442,883.021928,0.308177,22.73,656.33,2.481885,16.01,5.86,41.26,Bagerhat,28.25,1.811287,3.89,14.770987,5.73,301.581973,Loamy (Thịt/Phù sa),4.994778068,28.878197,70.0,54,49.52,No need to do,8.73,Mango,33.97,April,Kharif 1,0.267147

In [14]:
feature_group_summary = (
    feature_dictionary
    .groupby("Group")["Feature"]
    .apply(list)
    .reset_index()
)

feature_group_summary["num_features"] = feature_group_summary["Feature"].apply(len)
feature_group_summary

,Group,Feature,num_features
0,Agricultural indicator,[AP Ratio],1
1,Climate,"[Rain_Temp_Ratio, Rainfall, Wind_Mean, Temp_Mi...",8
2,Climate / Remote sensing,[LST_Kelvin],1
3,Climate stress,[Heat_Stress_Days],1
4,Crop,[Crop Name],1
5,Crop calendar,"[Growth, Transplant, Season]",3
6,Location,[District],1
7,Soil,"[Clay, Nitrogen, pH, Dominant_Soil_Texture, Si...",7
8,Soil / Climate,[Soil_Moisture_mm],1
9,Soil / Remote sensing,[Avg_Salinity_Index],1
10,Vegetation / Remote sensing,"[FPAR, EVI, LAI, NDVI_Season_Mean]",4